chore: refactoring

diff --git a/ubuntu-configure-desktop b/ubuntu-configure-desktop
--- a/ubuntu-configure-desktop
+++ b/ubuntu-configure-desktop
@@ -1,25 +1,33 @@
 #!/bin/bash
 set -e
 
+INSTALL=true
+CONFIGURE=true
+
 UBUNTU_RELEASE=jammy
 UBUNTU_VERSION=22.04
 NODEJS_VERSION=20
 MONGODB_VERSION=6.0
 
+APT_PACKAGES=(curl vim jq nmap calibre flameshot cheese ncdu tuxtype git cpu-x flatpak remmina-* python3-pip golang-go lua5.1 luarocks
+              apt-transport-https openssh-server bash-completion python3-gi libsqlite3-dev software-properties-common python3-gi-cairo
+              libbz2-dev csvkit make build-essential smartmontools gconf-service chntpw liblzma-dev golang-src lsb-release libffi-dev
+              gconf2 libgconf-2-4 libssl-dev gnupg2 zlib1g-dev gir1.2-gtk-3.0 libreadline-dev gnupg-agent libgdk-pixbuf2.0-0 dconf-editor)
 
-DEFAULT_APT_PACKAGES="curl vim jq nmap calibre flameshot cheese ncdu tuxtype git cpu-x flatpak remmina-* python3-pip golang-go lua5.1 luarocks csvkit make
-                      build-essential smartmontools apt-transport-https openssh-server bash-completion python3-gi libsqlite3-dev software-properties-common
-                      python3-gi-cairo gir1.2-gtk-3.0 libbz2-dev libreadline-dev gconf-service chntpw gnupg-agent liblzma-dev golang-src lsb-release libffi-dev
-                      gconf2 libgconf-2-4 libssl-dev gnupg2 zlib1g-dev libgdk-pixbuf2.0-0 dconf-editor"
-
-SYSTEM_PYTHON_PACKAGES="pipenv ansible openstacksdk azure-cli"
+PYTHON_PACKAGES=(
+  pipenv
+  ansible
+  openstacksdk
+  azure-cli
+  checkov
+)
 
 DEB_PACKAGES=(
   "https://packages.microsoft.com/config/ubuntu/${UBUNTU_VERSION}/packages-microsoft-prod.deb"
   "https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64"
 )
 
-APT_REPOSITORIES=(
+CUSTOM_APT_REPOSITORIES=(
   "github-cli,https://cli.github.com/packages stable main,https://cli.github.com/packages/githubcli-archive-keyring.gpg"
   "azure,https://packages.microsoft.com/repos/azure-cli/ ${UBUNTU_RELEASE} main,https://packages.microsoft.com/keys/microsoft.asc"
   "google-chrome,https://dl.google.com/linux/chrome/deb/ stable main,https://dl.google.com/linux/linux_signing_key.pub"
@@ -38,9 +46,9 @@ APT_REPOSITORIES=(
   "lens,https://downloads.k8slens.dev/apt/debian stable main,https://downloads.k8slens.dev/keys/gpg"
 )
 
-CUSTOM_APT_PACKAGES="spotify-client vault pgadmin4 postgresql-client-12 docker-ce nodejs mongodb-database-tools docker-compose terraform
+CUSTOM_APT_PACKAGES=(spotify-client vault pgadmin4 postgresql-client-12 docker-ce nodejs mongodb-database-tools docker-compose terraform
                      azure-cli helm kubectl google-cloud-sdk powershell dotnet-sdk-6.0 mongodb-mongosh google-chrome-stable yarn gh lens
-                     aztfexport aztfy virtualbox-7.0"
+                     aztfexport aztfy virtualbox-7.0 vlt)
 
 FLATPAKS=(
   com.github.IsmaelMartinez.teams_for_linux
@@ -53,11 +61,11 @@ FLATPAKS=(
 )
 
 ANSIBLE_COLLECTIONS=(
-  amazon.aws
-  openstack.cloud
+  ansible.posix
   community.docker
   community.general
-  ansible.posix
+  amazon.aws
+  openstack.cloud
   azure.azcollection
 )
 
@@ -74,119 +82,139 @@ HELM_REPOSITORIES=(
   "aws-secrets-manager,https://aws.github.io/secrets-store-csi-driver-provider-aws"
 )
 
+HELM_PLUGINS=(
+ https://github.com/helm-unittest/helm-unittest
+)
+
+NPM_PACKAGES=(
+  @vercel/ncc
+  typescript
+)
+
+GIT_CONFIGURATION_OPTIONS=(
+  "core.editor,vim"
+  "core.autocrlf,input"
+  "push.autoSetupRemote,true"
+  "push.followTags,true"
+  "init.defaultBranch,main"
+)
 
 ### Installation #############################################################################################
-if true; then
+if ${INSTALL}; then
 
+  # APT Packages ######################
   sudo add-apt-repository -y ppa:git-core/ppa
   sudo add-apt-repository -y universe
-  sudo apt-get upgrade -y
-  sudo apt-get install -y ${DEFAULT_APT_PACKAGES}
+  sudo apt-get install -y "${APT_PACKAGES[@]}"
 
-  # System python packages
-  sudo pip3 install --disable-pip-version-check --no-warn-conflicts --upgrade pipenv ${SYSTEM_PYTHON_PACKAGES}
+  # Python packages ###################
+  sudo pip3 install --disable-pip-version-check --no-warn-conflicts --upgrade pipenv "${PYTHON_PACKAGES[@]}"
 
-  # DEB packages
+  # DEB packages ######################
   for P in "${DEB_PACKAGES[@]}"; do
     ansible -i <(echo "{}") -b -o -m apt -a "deb=${P}" localhost
   done
 
-  # APT Repositories
-  for R in "${APT_REPOSITORIES[@]}"; do
+  # APT Repositories ##################
+  for R in "${CUSTOM_APT_REPOSITORIES[@]}"; do
     KEY="/usr/share/keyrings/$(echo "${R}"| cut -d, -f1)-archive-keyring.gpg"
     curl -fsSL "$(echo "${R}"| cut -d, -f3)" | gpg --dearmor | sudo tee "${KEY}" > /dev/null
     echo "deb [arch=amd64 signed-by=${KEY}] $(echo "${R}"| cut -d, -f2)" | sudo tee "/etc/apt/sources.list.d/$(echo "${R}"| cut -d, -f1).list"
   done
-  sudo apt-get install -y ${CUSTOM_APT_PACKAGES}
-  sudo apt-get upgrade -y
+  sudo apt-get install -y "${CUSTOM_APT_PACKAGES[@]}"
 
-  # NodeJS Packages
-  sudo npm install -g ncc typescript
+  # NodeJS Packages ###################
+  sudo npm install -g "${NPM_PACKAGES[@]}"
   sudo npm update -g
 
-  # Ansible Galaxy
+  # Ansible Galaxy ####################
   for U in "${ANSIBLE_COLLECTIONS[@]}"; do
     ansible-galaxy collection install --upgrade "${U}"
   done
 
-  # Flatpaks
+  # Flatpaks ##########################
   sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
   for F in "${FLATPAKS[@]}"; do
-    flatpak install --or-update -y "${F}"
+    flatpak install --noninteractive --or-update -y "${F}"
   done
 
-  # Helm repositories
+  # Helm repositories #################
   for R in "${HELM_REPOSITORIES[@]}"; do
     helm repo add "$(echo "${R}"| cut -d, -f1)" "$(echo "${R}"| cut -d, -f2)"
   done
-  helm repo update
+  helm repo update || true
 
-  # ZeroTier
+  # Helm plugins #################
+  for P in "${HELM_PLUGINS[@]}"; do
+    helm plugin install "${P}" || true
+  done
+
+  # ZeroTier ##########################
   curl -fsSL https://install.zerotier.com | sudo bash || true
 
-  # Rust
+  # Rust ##############################
   curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh /dev/stdin -y
 
-  # Pyenv
+  # Pyenv #############################
   "${HOME}/.pyenv/bin/pyenv" update || curl -fsSL https://pyenv.run | bash
 
-  # Terracognita
-  wget -q https://github.com/cycloidio/terracognita/releases/latest/download/terracognita-linux-amd64.tar.gz  -O - | sudo tar -xzvC /usr/local/bin/ --overwrite --transform='s/-linux-amd64//' -f - terracognita-linux-amd64
+  # Terracognita ######################
+  wget -q https://github.com/cycloidio/terracognita/releases/latest/download/terracognita-linux-amd64.tar.gz -O - | sudo tar -xzvC /usr/local/bin/ --overwrite --transform='s/-linux-amd64//' -f - terracognita-linux-amd64
 
-  # K9s
+  # K9s ###############################
   wget -q https://github.com/derailed/k9s/releases/latest/download/k9s_Linux_amd64.tar.gz -O - | sudo tar -xzvC /usr/local/bin/ --overwrite -f - k9s
 
-  # Eksctl
+  # Kubelogin #########################
+  wget -q https://github.com/Azure/kubelogin/releases/latest/download/kubelogin-linux-amd64.zip -O - | sudo busybox unzip -jo - bin/linux_amd64/kubelogin -d /usr/local/bin  && sudo chmod +x /usr/local/bin/kubelogin
+
+  # Kind ##############################
+  sudo wget -qO /usr/local/bin/kind https://github.com/kubernetes-sigs/kind/releases/latest/download/kind-linux-amd64
+
+  # Tilt ##############################
+  curl -fsSL https://raw.githubusercontent.com/tilt-dev/tilt/master/scripts/install.sh | bash
+
+  # AWS CLI ###########################
+  wget -q https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -O - | sudo busybox unzip -od /tmp - && sudo /tmp/aws/install --update && rm -rf /tmp/aws
+
+  # AWS Eksctl ########################
   wget -q https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_Linux_amd64.tar.gz -O - | sudo tar -xzvC /usr/local/bin/ --overwrite -f - eksctl
 
-  # Kubelogin
-  wget -qO /tmp/kubelogin-linux-amd64.zip "https://github.com/Azure/kubelogin/releases/latest/download/kubelogin-linux-amd64.zip"
-  sudo unzip -jo /tmp/kubelogin-linux-amd64.zip bin/linux_amd64/kubelogin -d /usr/local/bin
-  rm -rf /tmp/kubelogin-linux-amd64.zip
+  # Upgrade installed packages
+  sudo apt-get upgrade -y
 
-  # Kind
-  sudo wget -qO /usr/local/bin/kind "https://github.com/kubernetes-sigs/kind/releases/latest/download/kind-linux-amd64"
-  sudo chmod +x /usr/local/bin/kind
-
-  # AWS CLI
-  wget -qO /tmp/awscli-exe-linux-x86_64.zip https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
-  unzip -q /tmp/awscli-exe-linux-x86_64.zip -d /tmp
-  sudo /tmp/aws/install --update
-  rm -rf /tmp/aws*
-
+  # Clean up ##########################
   sudo apt-get clean
   sudo apt-get -y autoremove
 
 fi
 
 ### Configuration ################################################################################################
+if ${CONFIGURE}; then
 
-if true; then
+  # Passwordless sudo #################
+  echo "${USER} ALL=(ALL) NOPASSWD:ALL" | sudo tee "/etc/sudoers.d/${USER}"
 
-  # System
+  # System ############################
   sudo update-alternatives --set editor /usr/bin/vim.basic
 
-  # Docker
+  # Docker ############################
   sudo groupadd -f docker
-  sudo usermod -aG docker "$USER"
+  sudo usermod -aG docker "${USER}"
 
-  # GIT
-  git config --global core.editor vim
-  git config --global push.autoSetupRemote true
-  git config --global init.defaultBranch main
-  git config --global core.autocrlf input
+  # GIT ###############################
+  for O in "${GIT_CONFIGURATION_OPTIONS[@]}"; do
+    git config --global "$(echo "${O}"| cut -d, -f1)" "$(echo "${O}"| cut -d, -f2)"
+  done
 
-  # GitHub
+  # GitHub ############################
   gh config set git_protocol ssh -h github.com
 
-  # Custom bashrc commands
+  # Custom bashrc commands ############
   CUSTOM_BLOCK_HEAD="######## BEGIN CUSTOM COMMANDS ########"
   CUSTOM_BLOCK_TAIL="######### END CUSTOM COMMANDS #########"
-
   grep -qxF "${CUSTOM_BLOCK_HEAD}" "${HOME}/.bashrc" || printf "\n\n%s" "${CUSTOM_BLOCK_HEAD}" >> "${HOME}/.bashrc"
   grep -qxF "${CUSTOM_BLOCK_TAIL}" "${HOME}/.bashrc" || printf "\n%s" "${CUSTOM_BLOCK_TAIL}" >> "${HOME}/.bashrc"
-
-  CUSTOM_BLOCK_CONTENT=$(cat <<- 'EOF'
+  sed -i -ne "/${CUSTOM_BLOCK_HEAD}/ {p; r "<(cat <<- 'EOF'
 		# Pyenv
 		export PYENV_ROOT="$HOME/.pyenv"
 		command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
@@ -198,42 +226,41 @@ if true; then
 
 		# AWS
 		complete -C "$(which aws_completer)" aws
+		source <(eksctl completion bash)
 		alias aws_login='aws sso login --sso-session'
+
+    # Azure
+    source /etc/bash_completion.d/azure-cli
 
 		# Git
 		alias git_init='git init && git add . && git commit -m "chore: first commit"'
 		alias git_reset='rm -rf .git && git init'
 
 		# Github
-		GH_TOKEN=$(cat "${HOME}/.github_token" 2> /dev/null)
-		export GH_TOKEN
-		alias gh_tf_create='gh repo create ptonini/terraform-$(pwd | xargs basename) --public --source . --push'
+		export GH_TOKEN=$(cat "${HOME}/.github_token" 2> /dev/null)
+		source <(gh completion --shell bash)
+		alias gh_create_tf_mod='gh repo create ptonini/terraform-$(pwd | xargs basename) --public --source . --push && git push --tags'
 
 		# Kubeconfig
-		export KUBECONFIG=$HOME/.kube/config
+		export KUBECONFIG=${HOME}/.kube/config:${HOME}/.kube/terraform
 		source <(kubectl completion bash)
 
-		# Eksctl
-		source <(eksctl completion bash)
-
-		# Vault
-		export VAULT_ADDR=https://vault.nodis.com.br
+    # Vlt
+    alias vlt_get_tfvars='source .vltrc && vlt secrets get -o "${ORGANIZATION}" -p "${PROJECT}" -a "${APP_NAME}" --plaintext tfvars | jq > terraform.tfvars.json'
+    alias vlt_update_tfvars='source .vltrc && vlt secrets update -o "${ORGANIZATION}" -p "${PROJECT}" -a "${APP_NAME}" tfvars="$(cat terraform.tfvars.json)"'
 
 		# Terraform
-		export KUBE_CONFIG_PATH=$KUBECONFIG
-		export TF_VAR_kubeconfig=$KUBECONFIG
-		export TF_VAR_github_token=$GH_TOKEN
-		export TF_VAR_vault_addr=$VAULT_ADDR
 		alias tf_fmt='terraform fmt -recursive'
 		alias tf_get='terraform get'
 		alias tf_out='terraform output'
 		alias tf_unlock='terraform force-unlock -force'
 		alias tf_apply='terraform apply plan && rm -f plan'
-		alias tf_refresh='tf_fmt && tf_get && terraform plan -parallelism=50 -out=plan'
-		alias tf_plan='tf_refresh -refresh=false'
+		alias tf_plan_refresh='tf_fmt && tf_get && terraform plan -parallelism=50 -out=plan'
+		alias tf_plan='tf_plan_refresh -refresh=false'
 		alias tf_getup='tf_get -update'
 		alias tf_kube='tf_out -raw kubeconfig > "${HOME}/.kube/terraform" && chmod 0600 "${HOME}/.kube/terraform"'
-		alias tf_reset='rm -vrf .terraform && terraform init -backend-config=.encryption_key.gcs.tfbackend'
+		alias tf_reset='rm -vrf .terraform && terraform init'
+		alias tf_reset_gcs_encrypted='tf_reset -backend-config=.encryption_key.gcs.tfbackend'
 
 		# Golang
 		export GOPATH="$HOME/.go"
@@ -245,10 +272,11 @@ if true; then
 		# Kind
 		source <(kind completion bash)
 
+		# Tilt
+		source <(tilt completion bash)
+
 		# Rust
 		source "$HOME/.cargo/env"
 	EOF
-	)
-
-  sed -i -ne "/${CUSTOM_BLOCK_HEAD}/ {p; r "<(echo "${CUSTOM_BLOCK_CONTENT}") -e ":a; n; /${CUSTOM_BLOCK_TAIL}/ {p; b}; ba}; p" "${HOME}/.bashrc"
+	) -e ":a; n; /${CUSTOM_BLOCK_TAIL}/ {p; b}; ba}; p" "${HOME}/.bashrc"
 fi
